# Generated by Django 6.1 on 2026-09-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_replace_company_text_with_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('ONSITE', 'Onsite'), ('VIDEO', 'Video'), ('PHONE', 'Phone')], default='VIDEO', max_length=20)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
