from datetime import timedelta

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.db import transaction
from django.utils import timezone
from django.utils.text import slugify

from applications.models import Application, Company, Interview


COMPANIES = [
    ("TechNova", "Dhaka", "https://technova.example.com"),
    ("CloudWorks", "Remote", "https://cloudworks.example.com"),
    ("DataNest", "Chattogram", "https://datanest.example.com"),
    ("ByteCraft", "Dhaka", "https://bytecraft.example.com"),
    ("GreenSoft", "Sylhet", "https://greensoft.example.com"),
]

APPLICATIONS = [
    (0, "Backend Developer", "APPLIED", "REMOTE", 18, 65000),
    (0, "Python Developer", "INTERVIEW", "HYBRID", 12, 70000),
    (0, "Junior Django Developer", "WISHLIST", "ONSITE", None, 45000),
    (1, "API Engineer", "OFFER", "REMOTE", 30, 90000),
    (1, "Software Engineer", "APPLIED", "REMOTE", 5, 75000),
    (1, "Platform Engineer", "REJECTED", "REMOTE", 25, 85000),
    (2, "Data Engineer", "INTERVIEW", "HYBRID", 10, 80000),
    (2, "ETL Developer", "APPLIED", "ONSITE", 20, 60000),
    (2, "Analytics Engineer", "WISHLIST", "REMOTE", None, 70000),
    (3, "Django Developer", "REJECTED", "ONSITE", 40, 55000),
    (3, "Application Developer", "APPLIED", "HYBRID", 3, 62000),
    (3, "Systems Engineer", "INTERVIEW", "ONSITE", 8, 78000),
    (4, "Web Developer", "OFFER", "HYBRID", 22, 68000),
    (4, "Automation Engineer", "WISHLIST", "REMOTE", None, 72000),
    (4, "Associate Engineer", "REJECTED", "ONSITE", 15, 48000),
]


class Command(BaseCommand):
    help = "Create or refresh a complete JobTrail demo account."

    def add_arguments(self, parser):
        parser.add_argument("--username", default="demo")
        parser.add_argument("--email", default="demo@jobtrail.local")
        parser.add_argument("--password", required=True)
        parser.add_argument("--reset", action="store_true")

    @transaction.atomic
    def handle(self, *args, **options):
        User = get_user_model()
        user, _ = User.objects.get_or_create(
            username=options["username"],
            defaults={"email": options["email"]},
        )
        user.email = options["email"]
        user.set_password(options["password"])
        user.save(update_fields=["email", "password"])

        if options["reset"]:
            user.applications.all().delete()
            user.companies.all().delete()

        companies = []
        for name, location, website in COMPANIES:
            company, _ = Company.objects.update_or_create(
                owner=user,
                name=name,
                defaults={"location": location, "website": website},
            )
            companies.append(company)

        today = timezone.localdate()
        created_applications = {}

        for company_index, position, status, job_type, days, salary in APPLICATIONS:
            application, _ = Application.objects.update_or_create(
                owner=user,
                company=companies[company_index],
                position=position,
                defaults={
                    "status": status,
                    "job_type": job_type,
                    "applied_on": today - timedelta(days=days) if days else None,
                    "expected_salary": salary,
                    "job_link": f"https://jobs.example.com/{slugify(position)}",
                    "notes": "Demo application generated by seed_demo.",
                },
            )
            created_applications[position] = application

        for position, round_name, days in [
            ("Python Developer", "Technical interview", 2),
            ("Data Engineer", "Hiring manager interview", 5),
            ("Systems Engineer", "Final interview", 8),
        ]:
            Interview.objects.update_or_create(
                application=created_applications[position],
                round_name=round_name,
                defaults={
                    "scheduled_at": timezone.now() + timedelta(days=days),
                    "mode": Interview.Mode.VIDEO,
                    "result": Interview.Result.PENDING,
                    "notes": "Demo upcoming interview.",
                },
            )

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {user.username}: 5 companies, "
                "15 applications, and 3 interviews."
            )
        )